backend:
  name: github
  branch: main
  repo: eaton/quarantoons

site_url: "/"

media_folder: 'src/uploads/' # Media files will be stored in the repo under src/uploads
public_folder: '/uploads' # The src attribute for uploaded media will begin with /uploads

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:

  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    description: "News and notices for the gang."
    summary: "{{title}} — {{published}}"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "src/posts"
    create: true
    sortable_fields: ["title", "date", "author"]
    view_groups:
      - label: "Posted"
        field: "date"
        pattern: \d{4}
    fields:
      - { label: "Title", name: "title", widget: "string", required: true, pattern: ['.{0,60}', "60 characters max"], hint: "60 character limit; used in meta tags."  }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false, pattern: ['.{0,160}', "160 characters max"], hint: "Optional 160-char text used in listings and meta tags." }
      - { label: "Date published", name: "date", widget: "date", format: "YYYY-MM-DD", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "weeks"
    label: "Weeks"
    label_singular: "Week"
    description: "An individual playlist or collection of videos."
    summary: "{{date}} — {{curator}} — {{title}}"
    format: "frontmatter"
    slug: "{{week}}"
    folder: "src/weeks"
    create: true
    sortable_fields: ["title", "date", "curator"]
    fields:
      - { label: "Title", name: "title", widget: "string", required: false, pattern: ['.{0,60}', "60 characters max"], hint: "60 character limit; used in meta tags." }
      - { label: "Week", name: "week", widget: "number", value_type: "int", required: true }
      - { label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD", required: false }
      - name: "clips"
        label: "Clips"
        label_singular: "Clip"
        widget: "list"
        collapsed: false
        minimize_collapsed: true
        required: false
        hint: "YouTube playlists, YouTube videos, and Vimeo videos are supported."
        field: { label: "Clip Link", name: "link", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false, hint: "Optional thumbnail to use in the absence of a video." }
      - { label: "Curator", name: "curator", widget: "string", required: false }
      - { label: "Artist's Statement", name: "body", widget: "markdown", required: false }

